/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddComment`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddMeal`; params?: Router.UnknownInputParams; } | { pathname: `/components/InfoDate`; params?: Router.UnknownInputParams; } | { pathname: `/components/NavBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/NavBarTop`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProgressBarsKcal`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProgressBarsLitre`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProgressBarsMeal`; params?: Router.UnknownInputParams; } | { pathname: `/components/SafeArea`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/NutritionScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SportScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/TrackScreen`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AddComment`; params?: Router.UnknownOutputParams; } | { pathname: `/components/AddMeal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/InfoDate`; params?: Router.UnknownOutputParams; } | { pathname: `/components/NavBar`; params?: Router.UnknownOutputParams; } | { pathname: `/components/NavBarTop`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProgressBarsKcal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProgressBarsLitre`; params?: Router.UnknownOutputParams; } | { pathname: `/components/ProgressBarsMeal`; params?: Router.UnknownOutputParams; } | { pathname: `/components/SafeArea`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/NutritionScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/SportScreen`; params?: Router.UnknownOutputParams; } | { pathname: `/screens/TrackScreen`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/components/AddComment${`?${string}` | `#${string}` | ''}` | `/components/AddMeal${`?${string}` | `#${string}` | ''}` | `/components/InfoDate${`?${string}` | `#${string}` | ''}` | `/components/NavBar${`?${string}` | `#${string}` | ''}` | `/components/NavBarTop${`?${string}` | `#${string}` | ''}` | `/components/ProgressBarsKcal${`?${string}` | `#${string}` | ''}` | `/components/ProgressBarsLitre${`?${string}` | `#${string}` | ''}` | `/components/ProgressBarsMeal${`?${string}` | `#${string}` | ''}` | `/components/SafeArea${`?${string}` | `#${string}` | ''}` | `/screens/HomeScreen${`?${string}` | `#${string}` | ''}` | `/screens/NutritionScreen${`?${string}` | `#${string}` | ''}` | `/screens/SportScreen${`?${string}` | `#${string}` | ''}` | `/screens/TrackScreen${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddComment`; params?: Router.UnknownInputParams; } | { pathname: `/components/AddMeal`; params?: Router.UnknownInputParams; } | { pathname: `/components/InfoDate`; params?: Router.UnknownInputParams; } | { pathname: `/components/NavBar`; params?: Router.UnknownInputParams; } | { pathname: `/components/NavBarTop`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProgressBarsKcal`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProgressBarsLitre`; params?: Router.UnknownInputParams; } | { pathname: `/components/ProgressBarsMeal`; params?: Router.UnknownInputParams; } | { pathname: `/components/SafeArea`; params?: Router.UnknownInputParams; } | { pathname: `/screens/HomeScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/NutritionScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/SportScreen`; params?: Router.UnknownInputParams; } | { pathname: `/screens/TrackScreen`; params?: Router.UnknownInputParams; };
    }
  }
}
